# Generated by Django 5.1.2 on 2024-10-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_completed', 'Not completed'), ('completed', 'Completed')], default='not_completed', max_length=20),
        ),
    ]
